// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnauwoyjtpqekwxqxqlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYXV3b3lqdHBxZWt3eHF4cWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTc2NDEsImV4cCI6MjA2NTI5MzY0MX0.rn7Zn0FU_JT34q71JjyYdKUWp6IfUnkfdPzGzbjWYaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);